### PR TITLE
[WIP] Add a show route and view.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Add a new `show/:id` route and a placeholder view that returns the id.

### CODE REVIEW

**Comment by ericfranz** [comment]
You don't need to embed the entire ruby gem or npm package. Just use the distributed js file. I did a local test using https://cdnjs.com/libraries/turbolinks and it appeared to work fine.

The history of the change will appear to be "1 file added" instead of "58 files added" which is nice.

See PR https://github.com/OSC/ood-sacct/pull/2 for an example of this.

**Comment by ericfranz** [comment]
Note: you still have the challenge that by default:

1. a cached version of the view is used if the user navigates back using the history
2. a new version is requested from the server if the user clicks the "back"

The desired experience:

A new version is requested from the server only if the user clicks "Reload" on the browser OR clicks a button on the page that explicitly says "reload data".

**Comment by ericfranz** [comment]
`data-turbolinks-action="restore"` on the "Back" link might do it. See https://github.com/turbolinks/turbolinks#understanding-caching and https://github.com/turbolinks/turbolinks#restoration-visits

Seems like a gotcha could be if someone is expecting to be able to use jQuery or bootstrap jQuery components in a status app that they build on top of this, and don't realize the gotchas that exist because of turbolinks. It would appear to work on initial load, but then fail as soon as you navigate away and come back...

**Comment by brianmcmichael** [comment]
Your last point is the big issue with Turbolinks and seems to be one of the most common reasons that people have for removing it from their projects. Because it intercepts all clicks and even some JQuery handles, it can lead to unpredictable behavior for the unaware.

**Comment by ericfranz** [comment]
@brianmcmichael lets go ahead and git rm the source files for turbolinks, keeping the generated distribution js file. Then make a minified copy like you suggested, probably using https://www.npmjs.com/package/uglifyjs. This will ensure that we treat the turbolinks.js file in public/ the same way we treat the other two libs, bootstrap and jquery => where we just included the built distribution files.

Long term I imagine we will change this directory to be managed by yarn when we have nginx dependency update in Open OnDemand. At that point we will have a manually managed package.json that is easy to read and manage.

Until then, manually managing the files in public/ will be necessarily, so restricting the files we place there to the distribution versions will keep it simple for understanding purposes.

**Pull request merged**
